# nginx/nginx.conf
events {
    worker_connections 1024;
}

http {
    # Upstream definitions for load balancing
    upstream web_servers {
        server frontend:5173;
    }

    upstream api_servers {
        server backend:8000;
    }

    upstream elastic_servers {
        server es01:9200;
    }

    server {
        
        include nginx_base.conf;

        # Elastic search
        location /es/ {
            proxy_pass https://elastic_servers/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_ssl_trusted_certificate /etc/nginx/certs/ca/ca.crt; 
            proxy_ssl_verify on;
        }

        # Frontend routes
        location / {
            proxy_pass http://web_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Backend
        location /api/ {
            proxy_pass http://api_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

}